# Generated by Django 5.2.6 on 2025-10-03 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Item',
                'verbose_name_plural': 'Categorias de Itens',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
            },
        ),
        migrations.CreateModel(
            name='DoacaoRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(verbose_name='Data da Saída')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('entidade_gestora', models.ForeignKey(limit_choices_to={'eh_gestor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doacoes_distribuidas', to='crm.entidade')),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.DateField(verbose_name='Data da Doação')),
                ('object_id', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Doação Recebida',
                'verbose_name_plural': 'Doações Recebidas',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoriadeitens')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ItemDoacaoRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_doados', to='estoque.doacaorecebida')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item de Doação Recebida',
                'verbose_name_plural': 'Itens de Doações Recebidas',
            },
        ),
        migrations.CreateModel(
            name='ItemSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doacao_realizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_saida', to='estoque.doacaorealizada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item')),
            ],
        ),
        migrations.CreateModel(
            name='KitSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('doacao_realizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits_saida', to='estoque.doacaorealizada')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.kit')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo de Movimento')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.item', verbose_name='Item')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.item', verbose_name='Item')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_do_kit', to='estoque.kit')),
            ],
            options={
                'verbose_name': 'Item do Kit',
                'verbose_name_plural': 'Itens do Kit',
                'unique_together': {('kit', 'item')},
            },
        ),
    ]
