# Generated by Django 5.2.6 on 2025-09-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Item',
                'verbose_name_plural': 'Categorias de Itens',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='perecivel',
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(max_length=50, verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoriadeitens'),
        ),
    ]
