# Generated by Django 5.2.6 on 2025-09-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('estoque', '0002_categoriadeitens_remove_item_perecivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_doacao', models.DateField(verbose_name='Data da Doação')),
                ('object_id', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Doação Recebida',
                'verbose_name_plural': 'Doações Recebidas',
            },
        ),
        migrations.CreateModel(
            name='ItemDoacaoRecebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_doados', to='estoque.doacaorecebida')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item de Doação Recebida',
                'verbose_name_plural': 'Itens de Doações Recebidas',
            },
        ),
    ]
