# Generated by Django 5.2.6 on 2025-09-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('estoque', '0003_doacaorecebida_itemdoacaorecebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(verbose_name='Data da Saída')),
                ('object_id', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doacao_realizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_saida', to='estoque.doacaorealizada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.item')),
            ],
        ),
        migrations.CreateModel(
            name='KitSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('doacao_realizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits_saida', to='estoque.doacaorealizada')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.kit')),
            ],
        ),
    ]
