# Generated by Django 5.2.6 on 2025-09-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_entidade_eh_doador_entidade_eh_gestor'),
        ('estoque', '0004_doacaorealizada_itemsaida_kitsaida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacaorealizada',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='doacaorealizada',
            name='object_id',
        ),
        migrations.AddField(
            model_name='doacaorealizada',
            name='entidade_gestora',
            field=models.ForeignKey(limit_choices_to={'eh_gestor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doacoes_distribuidas', to='crm.entidade'),
        ),
    ]
