# Generated by Django 5.2.6 on 2025-10-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Entidade',
                'verbose_name_plural': 'Categorias de Entidades',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('documento', models.CharField(help_text='Informe CPF ou CNPJ', max_length=18, unique=True, verbose_name='CPF ou CNPJ')),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('data_cadastro', models.DateField(blank=True, null=True, verbose_name='Data de Cadastro Original')),
                ('vigencia_de', models.DateField(blank=True, null=True, verbose_name='Vigência De')),
                ('vigencia_ate', models.DateField(blank=True, null=True, verbose_name='Vigência Até')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('eh_doador', models.BooleanField(default=False, verbose_name='É Doador?')),
                ('eh_gestor', models.BooleanField(default=False, verbose_name='É Gestor/Recebedor?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.categoriaentidade', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[('T', 'Telefone'), ('E', 'Email')], max_length=1, verbose_name='Tipo de Contato')),
                ('valor', models.CharField(max_length=255, verbose_name='Contato')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='crm.entidade')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vinculo', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('entidade_intermediaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='crm.entidade', verbose_name='Entidade Intermediária')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pessoafisica', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Beneficiário',
                'verbose_name_plural': 'Beneficiários',
                'unique_together': {('entidade_intermediaria', 'pessoa_fisica')},
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='crm.entidade')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pessoafisica', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'unique_together': {('entidade', 'pessoa_fisica', 'cargo')},
            },
        ),
    ]
