# Generated by Django 5.2.6 on 2025-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Cadastro Original'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='vigencia_documento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vigência do Documento'),
        ),
    ]
