# Generated by Django 5.2.6 on 2025-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_entidade_data_cadastro_entidade_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='vigencia_documento',
        ),
        migrations.AddField(
            model_name='entidade',
            name='vigencia_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência Até'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='vigencia_de',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência De'),
        ),
    ]
