# Generated by Django 5.2.6 on 2025-10-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_drop_legacy_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('danger', 'danger')], default='warn', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='crm.entidade')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
