# Generated by Django 5.2.6 on 2025-09-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_entidade_vigencia_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='eh_doador',
            field=models.BooleanField(default=False, verbose_name='É Doador?'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='eh_gestor',
            field=models.BooleanField(default=False, verbose_name='É Gestor/Recebedor?'),
        ),
    ]
