# Generated by Django 5.2.6 on 2025-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_entidade_eh_doador_entidade_eh_gestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='endereco',
        ),
        migrations.AddField(
            model_name='entidade',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entidade',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='entidade',
            name='endereco_antigo',
            field=models.TextField(blank=True, verbose_name='Endereço Completo (Antigo)'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entidade',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
