# Generated by Django 5.2.6 on 2025-10-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_migrar_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='endereco_antigo',
        ),
    ]
